name: Singularity
on:
  push:
    branches:
      - scorpion

  # Test the build on all pull requests.
  pull_request: []

jobs:
  build-test-containers:
    name: Check Singularity build
    if: github.repository == 'jendrikseipp/scorpion'
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        singularity_version:
          - '3.8.1'

    container:
      image: quay.io/singularity/singularity:v${{ matrix.singularity_version }}
      options: --privileged

    steps:

      - name: Check out code for container builds
        uses: actions/checkout@v2

      - name: Build container
        run: |
          sudo -E singularity build container.sif Singularity

      - name: Login and deploy container
        if: (github.event_name != 'pull_request')
        run: |
          echo ${{ secrets.GITHUB_TOKEN }} | singularity remote login -u ${GITHUB_ACTOR} --password-stdin oras://ghcr.io
          singularity push container.sif oras://ghcr.io/${GITHUB_REPOSITORY}:latest
          # Image can now be pulled with "singularity pull oras://ghcr.io/${GITHUB_REPOSITORY}:latest"
          # Note that the pull fails for Singularity 3.5 but works for 3.8.
