---
name: Docs

on:
  push

jobs:
  autodoc:
    name: Build docs
    #if: github.repository == 'jendrikseipp/scorpion'
    timeout-minutes: 60
    runs-on: ubuntu-20.04
    steps:
      - name: Clone repository
        uses: actions/checkout@master

      - name: Install Python
        uses: actions/setup-python@master
        with:
          python-version: 3.8

      - name: Build site
        run: |
          cd misc/autodoc
          pip install -r requirements.txt
          python3 generate-docs.py
          mkdocs build

...
